spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dispatcher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql1114
    driver-class-name: com.mysql.cj.jdbc.Driver
    #nitialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #邮箱
  mail:
    host: smtp.163.com
    username: dispatchertest@163.com
    password: YAXMHJEHDHWSGULA
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mail:
  fromMail:
    addr: dispatchertest@163.com

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


#自定义的变量
dispatcher:
  task:
    pageSize: 20
    fileRootPathWIN: D:/dispatcher/file
  employee:
    pageSize: 20

server:
  port: 8080
