spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  #邮箱
  mail:
    host: smtp.163.com
    username: dispatchertest@163.com
    password: YAXMHJEHDHWSGULA
    default-encoding: UTF-8

mail:
  fromMail:
    addr: dispatchertest@163.com

#自定义的变量
dispatcher:
  task:
    pageSize: 10
    fileRootPathWIN: D:/dispatcher/file
  employee:
    pageSize: 10

