spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dispatcher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql1114
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
  servlet:
    multipart:
      max-request-size: 100MB
      enabled: true
      max-file-size: 100MB
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #邮箱
  mail:
    host: smtp.163.com
    username: dispatchertest@163.com
    password: YAXMHJEHDHWSGULA
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true



#自定义的变量
dispatcher:
  task:
    pageSize: 20
    fileRootPathWIN: D:/dispatcher/file
  employee:
    pageSize: 20
  commit:
    root: /Users/gud/Desktop/
  mail:
    fromMail:
      addr: dispatchertest@163.com

server:
  port: 8080
