spring:
  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dispatcher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wangwei1114
    driver-class-name: com.mysql.cj.jdbc.Driver
    #邮箱
  mail:
    host: smtp.163.com
    username: dispatchertest@163.com
    password: YAXMHJEHDHWSGULA
    default-encoding: UTF-8

mail:
  fromMail:
    addr: dispatchertest@163.com
